config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    devise_scope :user do
      authenticated :user do
      root 'cabins#index', as: :authenticated_root

    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  root 'cabins#index'
  get 'cabins/:id/index', to: 'reservations#index'
  get 'reservations', to: 'reservations#index', as: 'reservations'
  #get 'reservations/:id ', to: 'reservations#show', as: 'reservation'
  get 'cabins/:id/market', to: 'markets#show', as: 'market'
  get 'cabins/:cabin_id/reservations/:id/add_product', to: 'reservation_products#add', as:'reservation_products'
  get 'cabins/:cabin_id/reservations/:id/add_service', to: 'reservation_services#add', as:'reservation_services'
  get 'cabins/:cabin_id/reservations/:id/add_bicycle', to: 'reservation_bicycles#add', as:'reservation_bicycles'

  resources :customers
  resources :cabins do
    resources :products
    resources :services
    resources :bicycles do
      member do
        post :reservation
      end
    end
    resources :reservations, except: :destroy
  end

end

app/models/cabin.rb
# == Schema Information
#
# Table name: cabins
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cabin < ApplicationRecord
  has_many :reservations, :dependent => :delete_all
  has_many :customers , through:  :reservations
  has_many :bicycles, :dependent => :delete_all
  has_many :services, :dependent => :delete_all
  has_many :products, :dependent => :delete_all

  #Validaciones
  validates :name,
            presence: {message: ": No puede estar en blanco"},
            length: {minimun: 3, maximum: 20 }


end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
   load_and_authorize_resource
   before_action :set_cabin, only: [:show ,:edit, :update, :destroy]
   before_action :authenticate_user!


  #Pide todas las cabañas para luego listarlas
  def index
    @cabins = Cabin.all
  end

  #Crea un objeto cabaña vacio para poder mostrar la vista new
  def new
    @cabin = Cabin.new
  end

  #trae una cabaña respecto al id
  def show
    #set_cabin
    @reservations = @cabin.reservations.all
  end

  #crea cabaña
  def create
    @cabin = Cabin.new(cabin_params)
    if @cabin.save
      redirect_to cabins_path
    else
      render :new
    end
  end

  #manda a llamar una cabaña respecto al id para mostrar la vista edit
  def edit
    #set_cabin
  end

  #edit una cabaña respecto al id
  def update
    #set_cabin
    if @cabin.update(cabin_params)
      redirect_to @cabin
    else
      render :edit
    end
  end

  #llama una cabaña respecto a un id y luego la mestruye
  def destroy
    #set_params
    @cabin.destroy
  end

  private

  def cabin_params
    params.require(:cabin).permit(:name)
  end

  def set_cabin
    @cabin = Cabin.find(params[:id])
  end

end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/views/cabins/_formulario.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="form-horizontal">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for(@cabin) do |f| %>
        <p>
        <%=f.label :'Nombre Cabaña'%></br>
        <%=f.text_field :name %>
        </p>
             <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"><%=f.submit :Guardar, :class => 'btn btn-info'%></div>
            <div class="col-md-4"></div>
            </div>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/cabins/create.html.erb
<h1>Cabins#create</h1>
<p>Find me in app/views/cabins/create.html.erb</p>

app/views/cabins/destroy.html.erb
<h1>Cabins#destroy</h1>
<p>Find me in app/views/cabins/destroy.html.erb</p>

app/views/cabins/edit.js.erb
$('<%= j render 'formulario', title: "Editar Cabaña" %>').modal();

app/views/cabins/index.html.erb
<div class="container">
<div class="row">
  <div class="text-center col-md-12">
    <h3>Cabañas</h3>
  </div>

</div>
<table class="table table-bordered">
  <tr>
    <th>Nombre</th>
    <th>Acciones</th>
  </tr>

  <% @cabins.each do |cabin| %>
    <tr>
      <td><%= cabin.name %></td>

      <td><%= link_to 'Ver Calendario', cabin_path(cabin), :class  => 'btn btn-info' %>
      <% if can? :create, @user %>
      <%= link_to 'Reservar Cabaña', new_cabin_reservation_path(cabin), :class => 'btn btn-info'  %>
      <%= link_to 'Servicios Cabaña', market_path(cabin), :class  => 'btn btn-info' %>
      <%= link_to 'Editar Cabaña', edit_cabin_path(cabin), remote: true, :class => 'btn btn-warning'%>
      <%= link_to 'Eliminar Cabaña', cabin, :class => 'btn btn-danger',
                      method: :delete,
                      data: { confirm: '¿Estás seguro?' } %></td>
    <% end %>
    </tr>

  <% end %>
</table>
<div class="col-md-12">
  <% if can? :create, @user%>
  <%= link_to 'Agregar Cabaña', new_cabin_path, remote: true, :class => 'btn btn-primary btn-xs' %>
  <% end %>
  <%= link_to 'Pagina Inicio', root_path, :class => 'btn btn-info' %>
</div>

app/views/cabins/new.html.erb
<div class="container">
  <h1>Cabaña</h1>
<%= form_for [@cabin] do |f| %>
 <% if @cabin.errors.any? %>
 <div id="error_explanation">

   <ul>
     <% @cabin.errors.full_messages.each do |msg| %>
       <li  class="alert alert-danger" role="alert"><%= msg %></li>
     <% end %>
   </ul>
 </div>
<% end %>
<%=f.label :'Nombre Cabaña'%></br>
<%=f.text_field :name %>

   <%=f.submit :Guardar, :class => 'btn btn-info'%>
   </div>

   <% end %>
   </div>

app/views/cabins/show.html.erb
<div class="container">
  <div id="calendar"></div>
  <% if can? :create, @user %>
  <p class="py-5"><%= link_to 'Reserva', new_cabin_reservation_path(@cabin), :class => 'btn btn-info'  %></p>
  <%end%>
  <%= hidden_field_tag 'cabin_url', cabin_path(@cabin, format: 'json') %>
</div>

<script>
$(document).on("turbolinks:before-cache", function() {
  $('#calendar').fullCalendar('destroy');
})




      $(document).ready(function () {
          $("#calendar").fullCalendar({
                events: "/cabins/<%="#{@cabin.id}"%>.json"
          });
     });



</script>

app/views/cabins/update.html.erb
<h1>Cabins#update</h1>
<p>Find me in app/views/cabins/update.html.erb</p>