config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    devise_scope :user do
      authenticated :user do
      root 'cabins#index', as: :authenticated_root

    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  root 'cabins#index'
  get 'cabins/:id/index', to: 'reservations#index'
  get 'reservations', to: 'reservations#index', as: 'reservations'
  #get 'reservations/:id ', to: 'reservations#show', as: 'reservation'
  get 'cabins/:id/market', to: 'markets#show', as: 'market'
  get 'cabins/:cabin_id/reservations/:id/add_product', to: 'reservation_products#add', as:'reservation_products'
  get 'cabins/:cabin_id/reservations/:id/add_service', to: 'reservation_services#add', as:'reservation_services'
  get 'cabins/:cabin_id/reservations/:id/add_bicycle', to: 'reservation_bicycles#add', as:'reservation_bicycles'

  resources :customers
  resources :cabins do
    resources :products
    resources :services
    resources :bicycles do
      member do
        post :reservation
      end
    end
    resources :reservations, except: :destroy
  end

end

app/models/bicycle.rb
# == Schema Information
#
# Table name: bicycles
#
#  id         :bigint(8)        not null, primary key
#  model      :string
#  ring_size  :bigint(8)
#  tipo       :string
#  value      :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cabin_id   :bigint(8)
#  payment_id :bigint(8)
#
# Indexes
#
#  index_bicycles_on_cabin_id    (cabin_id)
#  index_bicycles_on_payment_id  (payment_id)
#
# Foreign Keys
#
#  fk_rails_...  (cabin_id => cabins.id)
#

class Bicycle < ApplicationRecord
	belongs_to :cabin
	has_many :bicycle_payments
	has_many :reservations , through: :bicycle_payments

	#Validaciones
	validates :model,
			  		presence: {message: ": No puede estar en blanco"},
			  		length: {minimun: 3, maximum: 20 }

    validates :ring_size,
    		  		presence: {message: ": No puede estar en blanco"}



    validates :tipo,
    		  		presence: {message: ": No puede estar en blanco"},
    		  		length: {minimun: 3, maximum: 20 }

    validates :value,
    		  		presence: {message: ": No puede estar en blanco"},
    		  		numericality: {only_integer: true, message: ": Solo puede contener números"}


end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :destroy, :reservation]
  before_action :authenticate_user!

  def index
    @bicycles = Bicycle.all
  end

  def show
    #set_params
  end

  def new
    @cabin = Cabin.find(params[:cabin_id])
    @bicycle = @cabin.bicycles.new
  end

  def create
    @cabin = Cabin.find(params[:cabin_id])
    @bicycle = @cabin.bicycles.new(bicycle_params)
    if @bicycle.save
      redirect_to market_path(@cabin)
    else
      render "new"
    end
  end

  def edit
    #set_params
  end

  def update
    #set_params
    if @bicycle.update(bicycle_params)
      redirect_to market_path(@cabin)
    else
      render "edit"
    end
  end

  def destroy
    #set_params
    @bicycle.destroy
  end

  def reservation
    reservation = Reservation.find(params[:reservation_id])
    bicycle_payment = BicyclePayment.new()
    bicycle_payment.reservation = reservation
    bicycle_payment.bicycle = @bicycle

    if bicycle_payment.save
      redirect_to reservation_bicycles_path(id: reservation.id, cabin_id: reservation.cabin_id), notice: "Bicicleta reservada con exito"
    else
      redirect_to reservation_bicycles_path(id: reservation.id, cabin_id: reservation.cabin_id), notice: "Error en la reserva de bicleta"
    end
  end

  private

  def set_params
    @cabin = Cabin.find(params[:cabin_id])
    @bicycle = @cabin.bicycles.find(params[:id])
  end

  def bicycle_params
    params.require(:bicycle).permit(:model, :ring_size, :tipo, :value)
  end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/_formulario.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="form-horizontal">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
        <%= form_for [@cabin,@bicycle] do |f| %>
          <p>
          <%=f.label :Modelo  %></br>
          <%=f.text_field :model %>
          </p>
          <p>
          <%=f.label :Aro %></br>
          <%=f.select :ring_size, options_for_select([
            ["Seleccione Aro", ""],
            "16",
            "20",
            "24",
            "26"]),
            {}, { class: "form form-group form-control" } %>
          </p>
          <p>
          <%=f.label :Tipo %></br>
          <%=f.select :tipo, options_for_select([
            ["Seleccione Una", ""],
            "Montaña",
            "Urbana",
            "Plegable"]),
            {}, { class: "form form-group form-control" } %>
          </p>
          <p>
          <%=f.label :Precio %></br>
          <%=f.text_field :value %>
          </p>
         <div class="row">
         <div class="col-md-4"></div>
         <div class="col-md-4"><%=f.submit :Guardar, :class => 'btn btn-info'%></div>
         <div class="col-md-4"></div>
         </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bicycles/create.html.erb
<h1>Bicycle#create</h1>
<p>Find me in app/views/bicycle/create.html.erb</p>

app/views/bicycles/destroy.html.erb
<h1>Bicycle#destroy</h1>
<p>Find me in app/views/bicycle/destroy.html.erb</p>

app/views/bicycles/edit.js.erb
$('<%= j render 'formulario', title: "Editar Bicicleta" %>').modal();

app/views/bicycles/index.html.erb
<table>
  <thead>
    <tr>
      <th> Modelo </th>
      <th> Tamaño del Aro </th>
      <th> Tipo </th>
      <th> Precio </th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |bicycle| %>
    <tr>
      <td> <%= bicycle.model %> </td>
      <td> <%= bicycle.ring_size %> </td>
      <td> <%= bicycle.type %> </td>
      <td> <%= bicycle.value %> </td>
      <%= link_to 'ver', bicycle_path(bicycle) %>
      <%= link_to 'editar', edit_bicycle_path(bicycle) %>
      <%= link_to 'eliminar', bicycle_path(bicycle),
                  method: :delete,
                  data: {confirm: '¿Estas seguro?'} %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
</br>
<%= link_to 'Nueva Bicicleta', new_bicycle_path %>

app/views/bicycles/new.html.erb
<div class="container">
  <h1>Producto</h1>
  <%= form_for [@cabin,@bicycle]  do |f| %>
  <% if @bicycle.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @bicycle.errors.full_messages.each do |msg| %>
            <li  class="alert alert-danger" role="alert"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @cabin.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@cabin.errors.count, "error") %>
          </h2>
          <ul>
            <% @cabin.errors.full_messages.each do |msg| %>
              <li  class="alert alert-danger" role="alert"><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <p>
        <%=f.label :Modelo  %></br>
        <%=f.text_field :model %>
        </p>
        <p>
        <%=f.label :Aro %></br>
        <%=f.select :ring_size, options_for_select([
          ["Seleccione Aro", ""],
          "16",
          "20",
          "24",
          "26"]),
          {}, { class: "form form-group form-control" } %>
        </p>
        <p>
          <%=f.label :Tipo %></br>
          <%=f.select :tipo, options_for_select([
            ["Seleccione Tipo", ""],
            "Montaña",
            "Urbana",
            "Plegable"]),
            {}, { class: "form form-group form-control" } %>
        </p>
        <p>
        <%=f.label :Precio %></br>
        <%=f.text_field :value %>
        </p>
        <%=f.submit :Guardar, :class => 'btn btn-info'%>
        </div>
        <% end %>
        </div>

app/views/bicycles/show.html.erb
<h1>Bicycle#show</h1>
<p> <%= @bicycle.model %> </p>
<p> <%= @bicycle.ring_size %> </p>
<p> <%= @bicycle.type %> </p>
<p> <%= @bicycle.value%> </p>
<%= link_to 'volver', bicycles_path %>

app/views/bicycles/update.html.erb
<h1>Bicycle#update</h1>
<p>Find me in app/views/bicycles/update.html.erb</p>