config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    devise_scope :user do
      authenticated :user do
      root 'cabins#index', as: :authenticated_root

    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  root 'cabins#index'
  get 'cabins/:id/index', to: 'reservations#index'
  get 'reservations', to: 'reservations#index', as: 'reservations'
  #get 'reservations/:id ', to: 'reservations#show', as: 'reservation'
  get 'cabins/:id/market', to: 'markets#show', as: 'market'
  get 'cabins/:cabin_id/reservations/:id/add_product', to: 'reservation_products#add', as:'reservation_products'
  get 'cabins/:cabin_id/reservations/:id/add_service', to: 'reservation_services#add', as:'reservation_services'
  get 'cabins/:cabin_id/reservations/:id/add_bicycle', to: 'reservation_bicycles#add', as:'reservation_bicycles'

  resources :customers
  resources :cabins do
    resources :products
    resources :services
    resources :bicycles do
      member do
        post :reservation
      end
    end
    resources :reservations, except: :destroy
  end

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
    before_action :authenticate_user!
  def index
  end

  def show
    @cabin = Cabin.find(params[:id])
    @services = @cabin.services.all
    @bicycles = @cabin.bicycles.all
    @products = @cabin.products.all
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/index.html.erb
<h1>Markets#index</h1>
<p>Find me in app/views/markets/index.html.erb</p>

app/views/markets/show.html.erb
<div class="container">
  <h1>Productos</h1>
  <td><%= link_to 'Agregar', new_cabin_product_path(@cabin), remote: true, :class => 'btn btn-primary' %></td>
  <table class="table table-bordered">
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>

    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %> </td>
        <td><%= link_to 'Editar', edit_cabin_product_path(@cabin ,product) , remote: true ,  :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Borrar', cabin_product_path(@cabin, product), :class => 'btn btn-danger',
                        method: :delete,
                        data: {confirm: '¿Estás seguro?'} %></td>

      </tr>
    <% end %>
  </table>

  <h1>Servicios</h1>
  <td><%= link_to 'Agregar', new_cabin_service_path(@cabin), remote: true, :class => 'btn btn-primary' %></td>
  <table class="table table-bordered">
    <tr>
      <th>Nombre</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>

    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.quantity %></td>
        <td><%= service.value %></td>
        <td><%= link_to 'Editar', edit_cabin_service_path(@cabin ,service) , remote: true ,  :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Borrar', cabin_service_path(@cabin, service), :class => 'btn btn-danger',
                        method: :delete,
                        data: {confirm: '¿Estás seguro?'} %></td>
      </tr>
    <% end %>
  </table>

  <h1>Bicicletas</h1>
  <td><%= link_to 'Agregar', new_cabin_bicycle_path(@cabin), remote: true, :class => 'btn btn-primary' %></td>
  <table class="table table-bordered">
    <tr>
      <th>Modelo</th>
      <th>Aro</th>
      <th>Tipo</th>
      <th>Precio</th>
    </tr>

    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.model %></td>
        <td><%= bicycle.ring_size %></td>
        <td><%= bicycle.tipo %></td>
        <td><%= bicycle.value %> </td>
        <td><%= link_to 'Editar', edit_cabin_bicycle_path(@cabin ,bicycle) , remote: true ,  :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Borrar', cabin_bicycle_path(@cabin, bicycle), :class => 'btn btn-danger',
                        method: :delete,
                        data: {confirm: '¿Estás seguro?'} %></td>

      </tr>
    <% end %>
  </table>

</div>