config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    devise_scope :user do
      authenticated :user do
      root 'cabins#index', as: :authenticated_root

    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
  root 'cabins#index'
  get 'cabins/:id/index', to: 'reservations#index'
  get 'reservations', to: 'reservations#index', as: 'reservations'
  #get 'reservations/:id ', to: 'reservations#show', as: 'reservation'
  get 'cabins/:id/market', to: 'markets#show', as: 'market'
  get 'cabins/:cabin_id/reservations/:id/add_product', to: 'reservation_products#add', as:'reservation_products'
  get 'cabins/:cabin_id/reservations/:id/add_service', to: 'reservation_services#add', as:'reservation_services'
  get 'cabins/:cabin_id/reservations/:id/add_bicycle', to: 'reservation_bicycles#add', as:'reservation_bicycles'

  resources :customers
  resources :cabins do
    resources :products
    resources :services
    resources :bicycles do
      member do
        post :reservation
      end
    end
    resources :reservations, except: :destroy
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint(8)        not null, primary key
#  description :string
#  name        :string
#  price       :bigint(8)
#  quantity    :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  cabin_id    :bigint(8)
#  payment_id  :bigint(8)
#
# Indexes
#
#  index_products_on_cabin_id    (cabin_id)
#  index_products_on_payment_id  (payment_id)
#
# Foreign Keys
#
#  fk_rails_...  (cabin_id => cabins.id)
#

class Product < ApplicationRecord
	belongs_to :cabin
	has_many :product_payments
	has_many :reservations , through: :product_payments

	#Validaciones
	validates :name,
			  		presence: {message: ": No puede estar en blanco"},
			  		length: {minimun: 3, maximum: 20 },
						uniqueness: true,
						format: {with: /\A[a-zA-Z0-9\s]+\z/i, message: ": Solo puede contener letras y números."}

	validates :description,
			  		presence: {message: ": No puede estar en blanco"},
			  		length: {minimun: 3, maximum: 40 },
						format: {with: /\A[a-zA-Z0-9\s]+\z/i, message: ": Solo puede contener letras y números."}

	validates :quantity,
					  presence: {message: ": No puede estar en blanco"},
					  numericality: {only_integer: true, message: ": Solo puede contener números"}

	validates :price,
					  presence: {message: ": No puede estar en blanco"},
					  numericality: {only_integer: true, message: ": Solo puede contener números"}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_params, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    #set_params
  end

  def new
    @cabin = Cabin.find(params[:cabin_id])
    @product = @cabin.products.new
  end

  def create
    @cabin = Cabin.find(params[:cabin_id])
    @product = @cabin.products.new(product_params)
    if @product.save
      redirect_to market_path(@cabin)
    else
      render :new
    end
  end

  def edit
    #set_params
  end

  def update
    #set_params
    if @product.update(product_params)
      redirect_back(fallback_location: 'something')
    else
      render "edit"
    end
  end

  def destroy
    #set_params
    @product.destroy
  end

  private

  def set_params
    @cabin = Cabin.find(params[:cabin_id])
    @product = @cabin.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :quantity, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_formulario.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="form-horizontal">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
        <%= form_for [@cabin,@product]   do |f| %>
          <p>
          <%=f.label :Nombre  %></br>
          <%=f.text_field :name %>
          </p>
          <p>
          <%=f.label :Descripcion %></br>
          <%=f.text_field :description %>
          </p>
          <p>
          <%=f.label :Cantidad %></br>
          <%=f.text_field :quantity %>
          </p>
          <p>
          <%=f.label :Precio %></br>
          <%=f.text_field :price %>
          </p>
          <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4"><%=f.submit :Guardar, :class => 'btn btn-info'%></div>
          <div class="col-md-4"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.js.erb
$('<%= j render 'formulario', title: "Editar producto" %>').modal();

app/views/products/index.html.erb
<table>
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Cantidad</th>
    <th>Precio</th>
    
  </tr>
  </thead>
  <tbody>
  <%@cabins.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.quantity %></td>
      <td><%= product.price %>
        <%= link_to 'ver', product_path(product) %>
        <%= link_to 'edit', edit_product_path(product) %>
        <%= link_to 'ELIMINAR', product_path(product),
                    method: :delete,
                    data: {confirm: '¿Estas seguro?'} %> </td>
    </tr>
  <% end %>
  </br>

  </tbody>
</table>
</br>
<%= link_to 'Nuevo Producto', new_product_path %>

app/views/products/new.html.erb
<div class="container">
  <h1>Producto</h1>
  <%= form_for [@cabin,@product]  do |f| %>
  <% if @product.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li  class="alert alert-danger" role="alert"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @cabin.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@cabin.errors.count, "error") %>
          </h2>
          <ul>
            <% @cabin.errors.full_messages.each do |msg| %>
              <li  class="alert alert-danger" role="alert"><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
  <p>
  <%=f.label :Nombre  %></br>
  <%=f.text_field :name %>
  </p>
  <p>
  <%=f.label :Descripcion %></br>
  <%=f.text_field :description %>
  </p>
  <p>
  <%=f.label :Cantidad %></br>
  <%=f.text_field :quantity %>
  </p>
  <p>
  <%=f.label :Precio %></br>
  <%=f.text_field :price %>
  </p>
<%=f.submit :Guardar, :class => 'btn btn-info'%>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<div class="container">
      <p> <%= @product.model %> </p>
      <p> <%= @product.ring_size %> </p>
      <p> <%= @product.type %> </p>
      <p> <%= @product.value%> </p>
      <%= link_to 'volver', products_path %>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>